 /*
 * #################################### TIMER0_config.h #############################
 *   Author : Aya Ramadan
 *   date   : 23 April 2024
 *   Layer  :MCAL
 *   SWC    :TIMER
 *   Version: 1
*/


#ifndef _TIMER_CONFIG_H_
#define _TIMER_CONFIG_H_

/*
  SET MODE
    1-TIMER0_NORMAL_MODE     
    2-TIMER0_PHASE_PWM_MODE  
    3-TIMER0_CTC_MODE        
    4-TIMER0_FAST_PWM_MODE   
*/

#define TIMER0_MODE  TIMER0_NORMAL_MODE


#if  TIMER0_MODE == TIMER0_NORMAL_MODE
    #define TIMER0_PRELOAD_VALE  0
	
#elif TIMER0_MODE == TIMER0_PHASE_PWM_MODE
 #define TIMER0_CTC_VALUE  200
/*
  COMPARE MATCH OUTPUT MODE PHASE CORRECT PWM MODE 
    1-TIMER0_DISCONNECTED_OC0  
    2-TIMER0_CLR_ON_CTC_UP_SET_DWONE_OC0        
    3-TIMER0_SET_ON_CTC_UP_CLR_DWONE_OC0        
*/
#define TIMER0_OC0_PHASE_PWM_MODE  TIMER0_CLR_ON_CTC_UP_SET_DWONE_OC0

#elif TIMER0_MODE == TIMER0_CTC_MODE
    #define TIMER0_CTC_VALUE  200
    /*
     SET THE COMPARE MATCH OUTPUT MODE FOR NON PWM 
      1-TIMER0_DISCONNECTED_OC0  
      2-TIMER0_TOGGLE_OC0        
      3-TIMER0_CLEAR_OC0         
      4-TIMER0_SET_OC0            
    */
    #define TIMER0_OC0_NON_PWM_MODE  TIMER0_TOGGLE_OC0

#elif TIMER0_MODE == TIMER0_FAST_PWM_MODE
 #define TIMER0_CTC_VALUE  200
/*
  COMPARE MATCH OUTPUT MODE FAST PWM MODE  
    1-TIMER0_DISCONNECTED_OC0  
    2-TIMER0_CLR_ON_CTC_SET_TOP_OC0       
    3-TIMER0_SET_ON_CTC_CLR_TOP_OC0         
*/
#define TIMER0_OC0_FAST_PWM_MODE  TIMER0_CLR_ON_CTC_SET_TOP_OC0

#endif

/*
 SET TIMER0 PRESCALLER  
    1-TIMER0_NO_CLOCK      
    2-TIMER0_NO_PRE        
    3-TIMER0_8_PRE         
    4-TIMER0_64_PRE        
    5-TIMER0_256_PRE       
    6-TIMER0_1024_PRE      
    7-TIMER0_EXT_FALLING   
    8-TIMER0_EXT_RISING    

*/

#define TIMER0_PRESCALLER   TIMER0_8_PRE


/*
 SET TIMER0 OVERFLOW INTERRUPT 
  1-TIMER0_INT_DISABLE_OVERFLOW
  2-TIMER0_INT_ENABLE_OVERFLOW
*/
#define TIMER0_OVERFLOW_INTERRUPT  TIMER0_INT_DISABLE_OVERFLOW

/*
 SET TIMER0 COMP_MATCH INTERRUPT 
   1-TIMER0_INT_DISABLE_COMP_MATCH
   2-TIMER0_INT_ENABLE_COMP_MATCH 
*/
#define TIMER0_COMP_MATCH_INTERRUPT  TIMER0_INT_DISABLE_COMP_MATCH

#endif